# fly.toml app configuration file generated for energymeasures on 2024-08-16T23:11:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'energymeasures'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8078
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
