name: API CD

on:
  push:
    tags:
      - v1.**
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: Azure/login@v1.4.5
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: Azure Container Registry Login
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az acr login -n crisagocmn.azurecr.io
  
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: 'src/'
      run: docker build . --file energymeasures/Dockerfile --tag crisagocmn.azurecr.io/pr114/emonitor:1.0\
      
    - name: Build the Docker image
      run: docker push crisagocmn.azurecr.io/pr114/emonitor:1.0
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: app-pr114-energyapi-01
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        #publish-profile: # optional
        # Enter an existing Slot other than the Production slot
        # slot-name: # optional, default is production
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        #package: # optional, default is .
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: crisagocmn.azurecr.io/pr114/emonitor:1.0 
        # Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
        # configuration-file: # optional
        # Enter the start up command. For ex. dotnet run or dotnet run
        # startup-command: # optional
