# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/web

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Application
        run: npm run build
      
      - name: List Files in Distribution Directory
        run: ls -R dist

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_LOGIN_PR114_EM_PRD }}
      
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name stopr114emp001 --auth-mode login -d '$web' -s ./src/web/dist/web
      
      # Azure logout
      - name: Azure logout
        run: |
              az logout
        if: always()
          
      
