name: API CD

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.5
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: crisagocmn
          # Container registry password
          password: ${{secrets.ACR_CRISAGOCMN_LOGIN}}
          # Container registry server url
          login-server: crisagocmn.azurecr.io

      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: 'src/'
        run: docker build . --file MyStromUploader/Dockerfile --tag crisagocmn.azurecr.io/pr114/MyStromUploader:1.0

      - name: Push docker image
        run: docker push crisagocmn.azurecr.io/pr114/MyStromUploader:1.0