name: MyStronUploader CD (Docker build)

on:
  push:
    branches:
      - main
    paths:
      'src/MyStromUploader/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  IMAGE_NAME: crisagocmn.azurecr.io/pr114/mystromuploader
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@1.4.6
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: crisagocmn
          password: ${{secrets.ACR_CRISAGOCMN_LOGIN}}
          login-server: crisagocmn.azurecr.io
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        working-directory: 'src/MyStromUploader/'
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          build-args: |
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
